server:
  port: 9091

spring:
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: teste
        secret-key: teste
      sqs:
        endpoint: ${SQS_ENDPOINT:http://localhost:4566/000000000000/fila-rj}

sistemaEstadoRJ:
  url: ${SISTEMA_ESTADO_RJ:http://localhost:3000}